travis:
  secure:
    BINSTAR_TOKEN: R42Pidi4MxYOIpxNYepquF1M2FE/EiHtM3g/rqf1L6Rn0R+4DTAY1aHz1U3lW0E4BqR0jtpVR6/eOI0EPGjdNLulVzVWSxtianFRgvR4do1VYTA8uoQJ5ZFrqfK+jcHWSq3qRFZg80drT22VK0tGGazQ2nLEcvmmmzvvQG2wocufbwyq+bKjSOIreLp82z4oIaaqN+a7nUj0kViSeQ2J4sMPZ0sg9yvAB8URN8ZIFxQuRf7b3V6dORbNQFWf0sP2rec2R4A0vikOzAbPZlLL5UvkwO6+9B0G2Pc1+n+3r6d3BCB22bB374RzJMhVhDHtPSvr79ar0WW61BA113V58CNpQ6UsvUZEhIQgWGyYllMAysF5/umTXluOVUdKxfv1EVsjsnvyb+rLkvW1twJIvpx1D6DWrasATdXfTCwTFDLj0DQStdDhO1KRycYUpyjauIDR7vKqT8otou907lHcosdVBSjPA5DECe0kdH55uS963MuYkjMyDSJObYM6q++NWaaoUgu5XCFpDrC/PDD2eW012dRtasc1/PgFRqNNR3EElFDlJGF+OrOXWfD+H0aw/CdY+kgnG+pfngEmnoX4HOcI8sncd76+/tIhMj9e4sjfMp2MHBHvsUVHBLO0rBGioq7tUhFwmAHUwX0Yk3SsPnTyTRDwmYXfAQj6cU7zc6E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
